# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\vscode_file\demo\vaoneGui\Datashow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatashowMainWindow(object):
    def setupUi(self, DatashowMainWindow):
        DatashowMainWindow.setObjectName("DatashowMainWindow")
        DatashowMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(DatashowMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.DatashowWidget = DataTableWidget(self.centralwidget)
        self.DatashowWidget.setObjectName("DatashowWidget")
        self.gridLayout.addWidget(self.DatashowWidget, 0, 0, 1, 1)
        DatashowMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DatashowMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        DatashowMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DatashowMainWindow)
        self.statusbar.setObjectName("statusbar")
        DatashowMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DatashowMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DatashowMainWindow)

    def retranslateUi(self, DatashowMainWindow):
        _translate = QtCore.QCoreApplication.translate
        DatashowMainWindow.setWindowTitle(_translate("DatashowMainWindow", "MainWindow"))
# from qtpandas.views.DataTableView import DataTableWidget
